Added auto migration from SWAG

diff --git a/root/etc/cont-init.d/20-config b/root/etc/cont-init.d/20-config
--- a/root/etc/cont-init.d/20-config
+++ b/root/etc/cont-init.d/20-config
@@ -32,6 +32,15 @@ mkdir -p \
   ln -s /swag/nginx/cloudflare.conf /config/nginx/cloudflare.conf
 [[ ! -f /config/nginx/dhparams.pem ]] &&
   ln -s /swag/nginx/dhparams.pem /config/nginx/dhparams.pem
+[[ ! -f /config/nginx/proxy.conf ]] &&
+  ln -s /swag/nginx/proxy.conf /config/nginx/proxy.conf
+
+cp -f /swag/nginx/site-confs/* /config/nginx/site-confs/ >/dev/null 2>&1
+
+sed -i \
+  -e 's/root .*;/root \/config\/public_html\/;/g' \
+  -e 's/index .*;/index index.html;/g' \
+  /config/nginx/site-confs/*
 
 # permissions
 chown -R abc:abc \
@@ -41,3 +50,9 @@ chown -R abc:abc \
 chmod -R g+w \
   /config/{nginx,public_html}
 chmod -R 644 /etc/logrotate.d
+
+if ! nginx -t -c /config/nginx/nginx.conf &>/dev/null; then
+  nginx -t -c /config/nginx/nginx.conf
+  echo "[cont-init.d] 20-config: Nginx config is invalid, Check your configs!"
+  sleep infinity
+fi
