add standalone mode

diff --git a/root/etc/cont-init.d/30-migrate b/root/etc/cont-init.d/30-migrate
--- a/root/etc/cont-init.d/30-migrate
+++ b/root/etc/cont-init.d/30-migrate
@@ -1,42 +1,44 @@
 #!/usr/bin/with-contenv bash
 
-# setup symlinks
-[[ ! -d /config/keys ]] &&
-	ln -s /swag/keys /config/keys
+if [ -d /swag ]; then
+	# setup symlinks
+	[[ ! -d /config/keys ]] &&
+		ln -s /swag/keys /config/keys
 
-# migrate SWAG configs
-cp -n \
-	/swag/nginx/site-confs/* \
-	/config/nginx/site-confs/ >/dev/null 2>&1
+	# migrate SWAG configs
+	cp -n \
+		/swag/nginx/site-confs/* \
+		/config/nginx/site-confs/ >/dev/null 2>&1
 
-# set root and index
-sed -i \
-	-e 's/root .*;/root \/config\/www\/;/g' \
-	-e 's/index .*;/index index.html;/g' \
-	/config/nginx/site-confs/*
+	# set root and index
+	sed -i \
+		-e 's/root .*;/root \/config\/www\/;/g' \
+		-e 's/index .*;/index index.html;/g' \
+		/config/nginx/site-confs/*
 
-# remove logs and potential linked w3 total cache confs
-sed -i \
-	-e '/access_log.*/d' \
-	-e '/error_log.*/d' \
-	-e '/include.*nginx.conf;/d' \
-	/config/nginx/site-confs/*
+	# remove logs and potential linked w3 total cache confs
+	sed -i \
+		-e '/access_log.*/d' \
+		-e '/error_log.*/d' \
+		-e '/include.*nginx.conf;/d' \
+		/config/nginx/site-confs/*
 
-# fix autoindex
-sed -i \
-	-e 's/autoindex index.html;/autoindex off;/g' \
-	/config/nginx/site-confs/*
+	# fix autoindex
+	sed -i \
+		-e 's/autoindex index.html;/autoindex off;/g' \
+		/config/nginx/site-confs/*
 
-for includes in $(cat /config/includes.txt); do
-	if [ ! -f /config/nginx/"$includes" ]; then
-		cp -f /swag/nginx/"$includes" /config/nginx/"$includes"
+	for includes in $(cat /config/includes.txt); do
+		if [ ! -f /config/nginx/"$includes" ]; then
+			cp -f /swag/nginx/"$includes" /config/nginx/"$includes"
+		fi
+	done
+
+	if ! nginx -t -c /config/nginx/nginx.conf &>/dev/null; then
+		nginx -t -c /config/nginx/nginx.conf
+		echo "Error: Nginx test failed, this is probably an error migrating your configs from SWAG. Update your configs in the maintenance appdata folder"
+		sleep infinity
 	fi
-done
-
-if ! nginx -t -c /config/nginx/nginx.conf &>/dev/null; then
-	nginx -t -c /config/nginx/nginx.conf
-	echo "Error: Nginx test failed, this is probably an error migrating your configs from SWAG. Update your configs in the maintenance appdata folder"
-	sleep infinity
 fi
 
 # permissions
